### ISSUE TITLE
Fatal error when $defaults is not set in image_resize_filter_form()

### ISSUE THREAD

**Issue by juanolalla** [backdrop-contrib/image_resize_filter#1]
I've got this error:
Fatal error: Unsupported operand types in image_resize_filter.module on line 148

Debugging it has shown that the reason is $defaults being asigned with the operator += when it is not set. The solution would be just to initialize the $defaults array.

**Comment by laryn** [comment]
I think this issue is not relevant anymore -- @juanolalla please correct me if I'm wrong!
