### ISSUE TITLE
PHP 8 deprecated ... passing null to param for remote images

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/image_resize_filter#12]
Just realized that this hasn't been reported yet.

How to reproduce:

- Enable to fetch remote images (configure filter on /admin/config/content/formats/filtered_html)
- Create content, open image dialog
- Put in a remote url, insert image
- Save the node

You get two deprecation notices with php 8:

```
Deprecated function: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in image_resize_filter_get_images() (line 185 of .../modules/image_resize_filter/image_resize_filter.module).
Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in image_resize_filter_get_images() (line 185 of .../modules/image_resize_filter/image_resize_filter.module).
```

At this point https://github.com/backdrop-contrib/image_resize_filter/blob/1.x-1.x/image_resize_filter.module#L183 `$local_path` is NULL.

A simple `!empty($local_path) && ...` should do the trick.

**Comment by laryn** [comment]
Thanks @indigoxela -- PR is ready for review.

**Comment by indigoxela** [comment]
Many thanks @laryn, works like a charm.

I tested resizing of regularly selected images (via library), local url direct input and remote image urls (with fetching enabled).

All work, all get resized and there's no more deprecation warning on php 8. :+1:
