### ISSUE TITLE
Any plans for next release?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/image_resize_filter#14]
Hi @laryn,

is there already a schedule for the next release? :smile_cat: 

Several issues have been fixed since 2021, these 10 commits look like worth for another release. Or are there show stoppers?

https://github.com/backdrop-contrib/image_resize_filter/compare/1.x-1.16.1...1.x-1.x

**Comment by laryn** [comment]
Good idea. I think maybe I was waiting to see if we got STR on https://github.com/backdrop-contrib/image_resize_filter/issues/6 and then forgot about it.
