### ISSUE TITLE
Fatal error when updating to 1.x-1.16.2

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/image_resize_filter#15]
When updating to the latest stable, one gets a fatal error and the site isn't accessible anymore (tested on two sites).

```
Error: Call to undefined function locale_language_negotiation_url_prefixes() in image_resize_filter_get_images() (168 ...modules/image_resize_filter/image_resize_filter.module).
```
This seems like (sort of) a regression from our attempt to remove the variable_get() usage.

Function function locale_language_negotiation_url_prefixes() ships with **core/includes/locale.inc** and is a simple wrapper to:
```
config_get('locale.settings', 'language_negotiation_url_prefixes');
```

Seems like the file isn't included at that point. Later the page works again, but immediately after updating, the site is broken, and no page is accessible (including the start page). So that's quite intimidating for admins.

My suggestion would be to switch to directly call config_get() instead, as that function is always available - also while updating.

**Comment by indigoxela** [comment]
@laryn a PR is available for testing and review. To test, you obviously need the locale/language modules enabled and a prefix configured.

**Comment by laryn** [comment]
Thanks @indigoxela -- that makes complete sense. I reviewed and am pushing a new release ASAP since this causes a fatal.
