### ISSUE TITLE
Module still uses deprecated variable_get() function

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/image_resize_filter#8]
References in module file:

https://github.com/backdrop-contrib/image_resize_filter/blob/1.x-1.x/image_resize_filter.module#L156

file_default_scheme is available as config via function file_default_scheme().

https://github.com/backdrop-contrib/image_resize_filter/blob/1.x-1.x/image_resize_filter.module#L331

Language and locale settings are available as config from language.settings.json and locale.settings.json.

**Comment by laryn** [comment]
Thank you, noted for when I work on this later!

**Comment by laryn** [comment]
@indigoxela Are you willing to test this one?
https://github.com/backdrop-contrib/image_resize_filter/pull/10

**Comment by indigoxela** [comment]
I did some basic testing and left a comment on your PR.

Please note: the module's functionality isn't actually broken (remote and "local remote" images get resized just fine). But one gets lots of "deprecated function variable_get()" nagging.

**Comment by laryn** [comment]
Thank you @indigoxela (and sorry about that).

I've updated the PR and stepped through in a dev environment so I think it should be working as expected without the deprecated calls.

**Comment by indigoxela** [comment]
@laryn no need to excuse, I'm glad you're working on it. :pray: 

Re the updated patch: uh-oh, things got worse. Now resizing of local images is actually broken and there's a php warning.

```
Warning: Undefined property: stdClass::$prefix in image_resize_filter_get_images() (line 162 of .../modules/image_resize_filter/image_resize_filter.module).
```
To reproduce, use a local image, but with the full url. I know, rather an edge case, as B has an image browser...

I belief, this has to do with the language object structure difference compared to D7.

```
  (object) array(
     'langcode' => 'de',
     'name' => 'German',
     'direction' => 0,
     'native' => 'Deutsch',
     'enabled' => true,
     'weight' => '-10',
     'default' => true,
  ),
```

**Comment by indigoxela** [comment]
Hm, the more I look at this code, the odder I find it (not your change, but the original code). :grin: 

This shouldn't take the langcode into account, but rather the path prefix, or am I missing something?

It's ancient code (D6), these were their issue and commit:

https://www.drupal.org/project/image_resize_filter/issues/921074

https://git.drupalcode.org/project/image_resize_filter/-/commit/4017bf722623ea73c9319c9619e7f9da6b2ea2de

**Comment by laryn** [comment]
@indigoxela 
Good catch -- I was not able to replicate the "resizing of local images is actually broken" part, but I think I've fixed the warning (and prefix functionality) in the latest commit to the PR. If the resizing is still broken, can you explain further how to replicate that?

**Comment by indigoxela** [comment]
Great, many thanks, it works correctly now and the nagging is gone.

It's probably not worth to further dig into this old code just for an edge case. The main purpose of this issue is to get rid of "variable_get", and the PR accomplishes that. :+1:
