### ISSUE TITLE
New option: convert to webp

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/image_resize_filter#9]
I'm thinking about adding a new configuration option (if the server supports it) to also convert to `webp` upon resizing. Anybody have any input or insights into that possibility that they'd like to raise/discuss? (cc @indigoxela)

**Comment by indigoxela** [comment]
That's probably a beneficial feature. For me personally probably not so important, as the resized images are usually relatively small, so the file size (and bandwidth) improvement isn't that important. Just my 2c. :wink:

**Comment by laryn** [comment]
As this may be a niche need I don't really want to introduce a lot of redundant code into this module. I think I'll allow this setting to be activated if the Image Effects > Coloractions and Conversion sub-module is active.
